travis:
  secure:
    BINSTAR_TOKEN: ji9Er4jZFg4g4GSd4yfukNuL3vixIOMwgHIXsll0r1Lo9zo7qXFubyAWQLL5OFxfMckSm7hDi65zbAJgYUwdYEiJwlvgUo+0JcQ9NxxdQXjFMVS9QfQM0HZxfaI/XgBIJPELNY7qoYQfzNiJU4oyzJsXKfcKVLH7z/j48lPKICaVnfbR7/6NHJQsUgp5T1FClDW0RPwgjVsU8uUcNxY4j1yBenvHIrEX3WStldYfpCj//zh+Kf6Uwr71BjeBgEJedkffZhlDz9stBYFXYRK15JafZBZeQwCn1e7qXGA8k0S+AGGR6f5wHISB5Z/ss2B0q7pVMW6P4ZLQir88kmwHQjXoKh/B9vFJSPpSaCmSubGTvf66/7fHQsi3oR+BBQWFonraVCekafrHy6EFUtWzuP4ulU7E453Q8h8viFACwb5a6UE0g1GaLBSqytnhszW8uPBMN3KCS4f/PNgH9+pFf7ydxIpgIQ+KqFSOHcHK4P14Jh0Rq0IaRzoK1ps682TdVuq6WplW28jk0IiiWSs39fVxU0/xDfdw0ttrCFiDelvuyHnObaY0/99R8rCjwvqhBqxBPkDVk51OU4RKtNUTO5iDEtrtJJ4dgu39cTGinC7HU8ZuE+QBbXZ0NM4x1wdUeVSPO147015Cg0RnhYLxU3UjJJKglWtdSc//ZdCVul4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
