travis:
  secure:
    BINSTAR_TOKEN: NBW4m3NSWRa5k4L1Lst2xjHvr53NLy8k+RhWNIt6lSvd8Liy01yCAw/+oyQU0y5PrKC3VlRZLl1DJXBZ6hC1psB0eELZ+epJhrIya5WjVblENAmmL0kcsV88VIHzjcCpvj4zf5bcwAVYRUQyn+/wcugtBJZpkWI9gaXJtCrb4/Kd00pe6cfhC0CVyiWaQ5E57gQntEmGt6w65CYS9eU44TZw7zkvv2HOu/2SZUhifsbsG9al1YiDIcJO6zqnITQxCiz+HCLr7GHdbkFqu5eem9k1E4t2bIr6o/ussvI783p9p+MNbv9Eggp1ZewNOgycb0jgrdTeQ569hbbmgP5IvXwl5p6yLksXVex53AzOmxyxQiUen9lAsSrr5zjSEFHNHq8iNQ/Jq21hxQMqdWtXzRIctnf/ag15WU1ZSH/RQB1MA8NTpc4mad9gWg0BEXUKz6CyOTvoCQj+wtzOHRNUmZsVzF5r458QyRHq0ZeXFIEvxjxF5ZNTvo/hc8lFGuVTUjxMApJf2nwFXo/k2QVmXQ3nTbJ67uYp9Ilpvs3eKFyzF6hOXxT3MGUPH0mj9O2y0k92c9U53rrc09d460YDMLLcN+SBQeTkUG6fslIpT6UCLb2oB+FbaOJmt2OHT+UeAgT4Ek+fZuS32Fq9ZnvcBv+vXSeXK3Q/uhF041c+eGE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
