travis:
  secure:
    BINSTAR_TOKEN: DAaot/ROVWHubMykOZP+v7nZZbYbVZHDWb/zU0VzUYZpRYDy54ZsTJAQIHpSNyK367NycyeP+ldLXW38sh2nYEE8ZRPS8UFQE0C96vhzcHq/xQcADQ+6sT8Ni/WBhLxC25UfHKfNY0h17U8k87Ce6QnEJpNBKhMXitG5XeV6886wQGXkLP4HO95id912R2jqSlUi4yWhfDt7VnWOKPrh3QVsGggebKwEFPRBpQeLZmckvnuTqXhmzAlhHKqvTn90L57h3NxBKMfK0NJTnzl93lVOfiDAgChQBEoMRjn7eRUDCRA+ZPtuYmxRkWW+3UY7SANxjjx5NFiqT72pLWoUdiVnBArpnHDQSOAXD/fQrt2CEOBIjMDyjXnW8fNpTqOnNnULLrTm7sjXY1WDUgHcbtx+MP7C8qCV3Yz+gUVfn2kueVoqFpf99ys7iqNXv0SJ0M8tJE2qQVKej8o+YtYZfQ1dgPNVD3dAATAsPnOHvEDADD+pXRXZ9r9ieG/jC7VygLuDESHP4bmY6NTbIA78HB4rdZReMDqpvVnJcxeqV9v+yfr+JxlTGZcDiSuQvtkg/DT4FiIt0tqHhVgn94dzJP8Bg7LhA3X8hhU+Ho+45UywbsHoOROw0/GY0+pk5etzWOlFhax8rUbVTP6DEeLj5cDuhwGCu0/rb57nEYG3FuE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
