appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: G5O553+rTDqpf61NuOnbRh8fQvcNgtvFRVTr69nKKrDemvlzkjogDYtB0ylJEYwmyWo63S3fKj9kpM3Ur+WoJMHk68BkOoFBVoC2Z1623W8a1fn6t0Ydt3z0Fl0GXiuyG+FmsdKSRFqXdaIwuaH8W/lVjf2fANMc+zI9LeW3paavIylHOIy865XWOUB8XzAWM5chGcgYkNg3XRrEmYQsAJmEd6gEHwBTR2bPrQOoDMq4lHLrb0drd3dqATHOiM37x2xtkjLxtKVQMzZMAcqt3SSQmxirIWZ2PRQqvLsnSD88HE7958TjA+FweDRp2zHohEMLiVYbpykIQWD6EEP0iVB1LzIw4tiBDzL0J3269XO1M1jKPH5xy5wKKlwMVqHMV9Q2VnrRNJ7tuSn67sD7clcxkj2rycWEqlaGi+T9wq4WXpSHLZC6Piu45eJ5eZZZRe0ViDryTDpSY4FYtUywcizJZmZ17TDO8aE63XWAmTlIApoAWYwHiY3hRWKv8IxHwp4Z8Qlis1nc1fWSeCqNMLgCqfohm9wY8ZKs61JjjnpMPcdvv506PL9rPemm6nvMdMqJ5qnhkcKa8pG31CfxO0TnhyfLl4wQqG03egTGeDllEHTsEvp+320TbncJ6UWEC70JEEoBIo+TLf0I8TjzSao0HOReEm8ct94/6AEYsE0=}
